logging:
  level:
    reactor:
      netty: INFO
    org:
      springframework:
        cloud:
          gateway: TRACE

spring:
  cloud:
    gateway:
      httpclient:
        wiretap: true
      httpserver:
        wiretap: true

services:
  control-panel:
    path: remote-falcon-control-panel
    uri: https://remotefalcon.dev/remote-falcon-control-panel
  viewer:
    path: remote-falcon-viewer
    uri: https://remotefalcon.dev/remote-falcon-viewer
  plugins-api:
    path: remote-falcon-plugins-api
    uri: https://remotefalcon.dev/remote-falcon-plugins-api