services:
  control-panel:
    path: remote-falcon-control-panel
    uri: http://localhost:8081/remote-falcon-control-panel
  viewer:
    path: remote-falcon-viewer
    uri: http://localhost:8082/remote-falcon-viewer
  plugins-api:
    path: remote-falcon-plugins-api
    uri: http://localhost:8083/remote-falcon-plugins-api

logging:
  level:
    org.springframework.web.HttpLogging: TRACE
    reactor.netty.http.server: DEBUG
    reactor.netty.http.client: DEBUG